project:
  type: website

website:
  title: "OW2 Season 4 Win Rate Prediction"
  navbar:
    left:
      - href: index.qmd
        text: OW2 Season 4
      - variables.qmd
      - model.qmd
      - graphs.qmd
      - sources.qmd
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



